language: go
go:
 - 1.5
 - 1.6
 - tip

sudo: false

before_install:
  - go get github.com/stretchr/testify/assert
  - go get -u github.com/golang/lint/golint
  - make deps

script:
  - golint
  - make build
  - make test
