language: go
go:
 - 1.11.x
 - master

sudo: false

# safelist branch to build
branches:
 only:
  - master

script:
 - make jenkins

notifications:
 email:
  - bifer@alea-soluciones.com

install:
 - sudo apt update
 - sudo apt install ca-certificates libgnutls30 -y
